# Generated by Django 4.2.4 on 2023-12-02 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_news_paper_delete_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.TextField()),
                ('paper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.news_paper')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.user')),
            ],
        ),
    ]
