# Generated by Django 4.2.4 on 2023-12-02 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_paper',
            name='user_id',
        ),
    ]
